title: Tom Bush
email: 28tbush@gmail.com
description: >-
  DPhil student in Artificial Intelligence at the University of Oxford.
baseurl: ""
url: "https://tuphs28.github.io"

theme: minima
github_username: tuphs28

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
